trigger:
    - master

pool:
    vmImage: 'windows-2019'

jobs:
    - job: Windows_Debug_Build
      steps:
        - template: .azurePipeline/build.yml
          parameters:
            configuration: Debug
    - job: Windows_Release_Build
      steps:
        - template: .azurePipeline/build.yml
          parameters:
            configuration: Release
