trigger:
    - master

jobs:
  - job: Cppecheck
    strategy:
      matrix:
        mac_debug:
          imageName: 'macOS-10.15'
          build_configuration: Debug
        mac_release:
          imageName: 'macOS-10.15'
          build_configuration: Release
        windows_vs_2017_debug:
          imageName: 'vs2017-win2016'
          build_configuration: Debug
        windows_vs_2017_release:
          imageName: 'vs2017-win2016'
          build_configuration: Release
        windows_vs_2019_debug:
          imageName: 'windows-2019'
          build_configuration: Debug
        windows_vs_2019_release:
          imageName: 'windows-2019'
          build_configuration: Release
    steps:
      - template: .azurePipeline/build.yml
        parameters:
          configuration: $(build_configuration)
    pool:
      vmImage: $(imageName)
