trigger:
    - master

jobs:
  - job: Debug_Build
    strategy:
      matrix:
        mac:
          imageName: 'macOS-10.15'
        windows:
          imageName: 'vs2017-win2016'
    steps:
      - template: .azurePipeline/build.yml
        parameters:
          configuration: Debug
    pool:
      vmImage: $(imageName)
  - job: Release_Build
    strategy:
      matrix:
        mac:
          imageName: 'macOS-10.15'
        windows:
          imageName: 'vs2017-win2016'
    steps:
      - template: .azurePipeline/build.yml
        parameters:
          configuration: Release
    pool:
      vmImage: $(imageName)
