
parameters:
    - name: configuration
      type: string
      default: Debug

steps:
    - script: |
        choco install conan
        choco install cppcheck
        refreshenv
      displayName: Install dependencies
    - bash: |
        mkdir -p build
        cd build
        cmake .. -DRUN_CPPCHECK=ON
      displayName: Generate the soltuion
    - bash: |
        cd build
        cmake --build . --config ${{ parameters.configuration }}
        error_code=$?
        if [[ $error_code -eq 0 ]]; then
          exit 1
        fi
        exit 0
      displayName: Build the soltuion
